// Code generated by "go-enum -type FileType -trimprefix=FileType --transform=upper"; DO NOT EDIT.

package webhdfs

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileTypeFile-0]
	_ = x[Directory-1]
	_ = x[Symlink-2]
}

const _FileType_name = "FILEDIRECTORYSYMLINK"

var _FileType_index = [...]uint8{0, 4, 13, 20}

func _() {
	var _nil_FileType_value = func() (val FileType) { return }()

	// An "cannot convert FileType literal (type FileType) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_FileType_value
}

func (i FileType) String() string {
	if i < 0 || i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}

var _FileType_values = []FileType{0, 1, 2}

var _FileType_name_to_values = map[string]FileType{
	_FileType_name[0:4]:   0,
	_FileType_name[4:13]:  1,
	_FileType_name[13:20]: 2,
}

// ParseFileTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseFileTypeString(s string) (FileType, error) {
	if val, ok := _FileType_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FileType values", s)
}

// FileTypeValues returns all values of the enum
func FileTypeValues() []FileType {
	return _FileType_values
}

// IsAFileType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FileType) Registered() bool {
	for _, v := range _FileType_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_FileType_value = func() (val FileType) { return }()

	// An "cannot convert FileType literal (type FileType) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_FileType_value

	// An "cannot convert FileType literal (type FileType) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_FileType_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for FileType
func (i FileType) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for FileType
func (i *FileType) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseFileTypeString(string(data))
	return err
}

func _() {
	var _nil_FileType_value = func() (val FileType) { return }()

	// An "cannot convert FileType literal (type FileType) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_FileType_value

	// An "cannot convert FileType literal (type FileType) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_FileType_value
}

// MarshalJSON implements the json.Marshaler interface for FileType
func (i FileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FileType
func (i *FileType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FileType should be a string, got %s", data)
	}

	var err error
	*i, err = ParseFileTypeString(s)
	return err
}

func _() {
	var _nil_FileType_value = func() (val FileType) { return }()

	// An "cannot convert FileType literal (type FileType) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_FileType_value

	// An "cannot convert FileType literal (type FileType) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_FileType_value
}

// MarshalText implements the encoding.TextMarshaler interface for FileType
func (i FileType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FileType
func (i *FileType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseFileTypeString(string(text))
	return err
}

//func _() {
//	var _nil_FileType_value = func() (val FileType) { return }()
//
//	// An "cannot convert FileType literal (type FileType) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_FileType_value
//
//	// An "cannot convert FileType literal (type FileType) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_FileType_value
//}

// MarshalYAML implements a YAML Marshaler for FileType
func (i FileType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for FileType
func (i *FileType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseFileTypeString(s)
	return err
}

func _() {
	var _nil_FileType_value = func() (val FileType) { return }()

	// An "cannot convert FileType literal (type FileType) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_FileType_value

	// An "cannot convert FileType literal (type FileType) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_FileType_value
}

func (i FileType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *FileType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseFileTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// FileTypeSliceContains reports whether sunEnums is within enums.
func FileTypeSliceContains(enums []FileType, sunEnums ...FileType) bool {
	var seenEnums = map[FileType]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// FileTypeSliceContainsAny reports whether any sunEnum is within enums.
func FileTypeSliceContainsAny(enums []FileType, sunEnums ...FileType) bool {
	var seenEnums = map[FileType]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
