// Code generated by "go-enum -type XAttrValueEncoding --linecomment"; DO NOT EDIT.

package webhdfs

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[XAttrValueEncodingText-0]
	_ = x[XAttrValueEncodingHex-1]
	_ = x[XAttrValueEncodingBase64-2]
}

const _XAttrValueEncoding_name = "texthexbase64"

var _XAttrValueEncoding_index = [...]uint8{0, 4, 7, 13}

func _() {
	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_XAttrValueEncoding_value
}

func (i XAttrValueEncoding) String() string {
	if i < 0 || i >= XAttrValueEncoding(len(_XAttrValueEncoding_index)-1) {
		return "XAttrValueEncoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _XAttrValueEncoding_name[_XAttrValueEncoding_index[i]:_XAttrValueEncoding_index[i+1]]
}

// New returns a pointer to a new addr filled with the XAttrValueEncoding value passed in.
func (i XAttrValueEncoding) New() *XAttrValueEncoding {
	clone := i
	return &clone
}

var _XAttrValueEncoding_values = []XAttrValueEncoding{0, 1, 2}

var _XAttrValueEncoding_name_to_values = map[string]XAttrValueEncoding{
	_XAttrValueEncoding_name[0:4]:  0,
	_XAttrValueEncoding_name[4:7]:  1,
	_XAttrValueEncoding_name[7:13]: 2,
}

// ParseXAttrValueEncodingString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseXAttrValueEncodingString(s string) (XAttrValueEncoding, error) {
	if val, ok := _XAttrValueEncoding_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to XAttrValueEncoding values", s)
}

// XAttrValueEncodingValues returns all values of the enum
func XAttrValueEncodingValues() []XAttrValueEncoding {
	return _XAttrValueEncoding_values
}

// IsAXAttrValueEncoding returns "true" if the value is listed in the enum definition. "false" otherwise
func (i XAttrValueEncoding) Registered() bool {
	for _, v := range _XAttrValueEncoding_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_XAttrValueEncoding_value

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_XAttrValueEncoding_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for XAttrValueEncoding
func (i XAttrValueEncoding) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for XAttrValueEncoding
func (i *XAttrValueEncoding) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseXAttrValueEncodingString(string(data))
	return err
}

func _() {
	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_XAttrValueEncoding_value

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_XAttrValueEncoding_value
}

// MarshalJSON implements the json.Marshaler interface for XAttrValueEncoding
func (i XAttrValueEncoding) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for XAttrValueEncoding
func (i *XAttrValueEncoding) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("XAttrValueEncoding should be a string, got %s", data)
	}

	var err error
	*i, err = ParseXAttrValueEncodingString(s)
	return err
}

func _() {
	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_XAttrValueEncoding_value

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_XAttrValueEncoding_value
}

// MarshalText implements the encoding.TextMarshaler interface for XAttrValueEncoding
func (i XAttrValueEncoding) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for XAttrValueEncoding
func (i *XAttrValueEncoding) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseXAttrValueEncodingString(string(text))
	return err
}

//func _() {
//	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()
//
//	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_XAttrValueEncoding_value
//
//	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_XAttrValueEncoding_value
//}

// MarshalYAML implements a YAML Marshaler for XAttrValueEncoding
func (i XAttrValueEncoding) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for XAttrValueEncoding
func (i *XAttrValueEncoding) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseXAttrValueEncodingString(s)
	return err
}

func _() {
	var _nil_XAttrValueEncoding_value = func() (val XAttrValueEncoding) { return }()

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_XAttrValueEncoding_value

	// An "cannot convert XAttrValueEncoding literal (type XAttrValueEncoding) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_XAttrValueEncoding_value
}

func (i XAttrValueEncoding) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *XAttrValueEncoding) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseXAttrValueEncodingString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// XAttrValueEncodingSliceContains reports whether sunEnums is within enums.
func XAttrValueEncodingSliceContains(enums []XAttrValueEncoding, sunEnums ...XAttrValueEncoding) bool {
	var seenEnums = map[XAttrValueEncoding]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// XAttrValueEncodingSliceContainsAny reports whether any sunEnum is within enums.
func XAttrValueEncodingSliceContainsAny(enums []XAttrValueEncoding, sunEnums ...XAttrValueEncoding) bool {
	var seenEnums = map[XAttrValueEncoding]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
